- app/controllers/menu_items_controller.rb
- app/models/menu_item.rb
- app/views/menu_items/index.html.erb
- config/routes.rb
- db/migrate/20210824213926_create_menu_items.rb
- db/schema.rb
Created the first migration of data for menu items
> Database setup

- app/controllers/drinks_controller.rb
- app/models/drink.rb
- app/views/drinks/index.html.erb
- config/routes.rb
- db/migrate/20210825001547_create_drinks.rb
- db/schema.rb
What I did: Create a Drinks table that shows on the local host
> Add drinks table

- app/controllers/bar_drinks_controller.rb
- app/controllers/bars_controller.rb
- app/models/bar.rb
- app/views/bar_drinks/index.html.erb
- app/views/bars/index.html.erb
- app/views/bars/show.html.erb
- app/views/drinks/show.html.erb
- config/routes.rb
- db/schema.rb
- db/seeds.rb
- spec/features/bars/drinks/index_spec.rb
- spec/features/bars/index_spec.rb
- spec/features/bars/show_spec.rb
- spec/features/drinks/show_spec.rb
- spec/models/bar_spec.rb
- spec/models/drink_spec.rb
- spec/models/drinks_spec.rb
What I did:
Completed and tested user stories up until story 7.
> Links and tests

- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
- spec/features/bars/drinks/index_spec.rb
- spec/features/bars/index_spec.rb
- spec/features/bars/show_spec.rb
- spec/features/drinks/show_spec.rb
- spec/features/menu_items/index_spec.rb
- spec/features/menu_items/show_spec.rb
- spec/features/restaurants/index_spec.rb
- spec/features/restaurants/new_spec.rb
- spec/features/restaurants/restaurant_menu_items_spec.rb
- spec/features/restaurants/show_spec.rb
Created nav bar for all index pages. Testing completed in all feature spec files
> Add testing to all spec files for the nav links

- app/views/bars/show.html.erb
- app/views/layouts/_header.html.erb
- app/views/menu_items/index.html.erb
- app/views/menu_items/show.html.erb
- app/views/restaurants/index.html.erb
- app/views/restaurants/new.html.erb
- app/views/restaurants/restaurant_menu_items.html.erb
- app/views/restaurants/show.html.erb
- config/routes.rb
Updated files so links are no longer included. Fixed bug in accessing restaurant show pages
> Andrew feature tests

- app/views/bars/show.html.erb
- spec/features/bars/index_spec.rb
- spec/features/bars/show_spec.rb
Resolved merge conflict and completed user story 10 by adding a link to the child table at the top of the parent page
> User story 10

- app/views/bars/index.html.erb
- spec/features/bars/index_spec.rb
Finish up user story 6 and add bar links to the Bar index page
> Finish up user story 6 and add links to the bars index

- db/seeds.rb
Added my seeds to seeds.rb so we have access to eachothers data
> Create seeds for database

- app/controllers/restaurants_controller.rb
- app/views/restaurants/edit.html.erb
- app/views/restaurants/show.html.erb
- config/routes.rb
- spec/features/restaurants/edit_spec.rb
Create functionality to edit parents
> Parent edit

- app/controllers/drinks_controller.rb
- app/models/drink.rb
- app/views/bars/show.html.erb
- db/seeds.rb
- spec/features/bars/drinks/index_spec.rb
- spec/features/bars/new_spec.rb
- spec/features/bars/show_spec.rb
- spec/features/drinks/index_spec.rb
- spec/models/drink_spec.rb
What I did:
Made a link to find all of the drink booleans that return true
> Child boolean index

- app/views/bars/show.html.erb
- db/seeds.rb
- spec/features/bars/drinks/index_spec.rb
- spec/features/bars/new_spec.rb
- spec/features/bars/show_spec.rb
What I did:
Add part of the update form test and change seeds
> Add update form for bar show page and seeds

- app/controllers/bars_controller.rb
- app/views/bars/edit.html.erb
- app/views/bars/show.html.erb
- config/routes.rb
- spec/features/bars/edit_spec.rb
- spec/features/bars/show_spec.rb
What I did:
Organized routes and created an update page to change the Bar attributes
> User story 12

- app/controllers/menu_items_controller.rb
- app/models/menu_item.rb
- app/views/menu_items/index.html.erb
- app/views/restaurant_menu_items/index.html.erb
- app/views/restaurants/index.html.erb
- spec/features/menu_items/index_spec.rb
- spec/features/restaurants/index_spec.rb
- spec/features/restaurants/menu_items/index_spec.rb
What I did: 
User story 17 && 18
> Children index edit links

- app/controllers/menu_items_controller.rb
- app/models/menu_item.rb
- spec/features/menu_items/index_spec.rb
What I did: Complete user story 15
> Only true child index

- app/controllers/bar_drinks_controller.rb
- app/views/bar_drinks/index.html.erb
- app/views/bar_drinks/new.html.erb
- app/views/bars/index.html.erb
- app/views/bars/new.html.erb
- config/routes.rb
- spec/features/bars/drinks/index_spec.rb
- spec/features/bars/drinks/new_spec.rb
- spec/features/bars/new_spec.rb
What I did:
Create a Bar drinks edit page.
> Create a drink creation form and update form button

- app/controllers/drinks_controller.rb
- app/views/drinks/edit.html.erb
- app/views/drinks/show.html.erb
- config/routes.rb
- spec/features/drinks/edit_spec.rb
What I did:
Created a button to update a created drink and then redirect the user back to the drinks index
> Create an update form for the drink forms

- app/controllers/restaurant_menu_items_controller.rb
- app/models/menu_item.rb
- app/views/restaurant_menu_items/index.html.erb
- spec/features/restaurants/menu_items/index_spec.rb
- spec/models/menu_item_spec.rb
- spec/models/restaurant_spec.rb
What I did: 
Set up query param for ordering parent child index alphabetically
> Parent child alphabetize

- app/controllers/bar_drinks_controller.rb
- app/models/drink.rb
- app/views/bar_drinks/index.html.erb
- spec/features/bars/drinks/index_spec.rb
- spec/models/drink_spec.rb
What I did:
Added a button to the bar drinks page that alphabetizes the drinks and wrote tests for this feature.
> Add button to alphabetize the bar drinks

- app/views/bars/index.html.erb
- spec/features/bars/index_spec.rb
what I did:
Added a buttons to the bar index page that redirects you to the bar edit form. I also wrote tests for these buttons.
> Add button to the bar index that redirects to the edit bar form

- app/controllers/bars_controller.rb
- app/views/bars/show.html.erb
- config/routes.rb
- spec/features/bars/show_spec.rb
What I did:
Created a form to delete a bar from the show page and all the children associated to it. Also, wrote dynamic tests in the show spec to make sure it works.
> Add form to destroy the bar and drinks

- app/controllers/restaurants_controller.rb
- app/views/restaurants/show.html.erb
- config/routes.rb
- spec/features/restaurants/menu_items/index_spec.rb
- spec/features/restaurants/show_spec.rb
What I did:
Create functionality to delete a parent with all of its children
> Parent delete

- app/controllers/drinks_controller.rb
- app/views/drinks/show.html.erb
- config/routes.rb
- spec/features/bars/edit_spec.rb
- spec/features/drinks/show_spec.rb
What I did:
Created a link to delete a drink from the drink show page.  Implemented tests to make sure the drink successfully deletes from the database.
> Create a link to delete a drink

- app/controllers/menu_items_controller.rb
- app/views/menu_items/show.html.erb
- config/routes.rb
- spec/features/menu_items/show_spec.rb
What I did:
Create delete link for menu items from the index page
> Child delete

- app/views/bars/index.html.erb
- spec/features/bars/index_spec.rb
What I did:
Add delete bar button to each bar in the bar index.
> Add delete bar button next to each bar in the index

- app/views/menu_items/index.html.erb
- app/views/restaurant_menu_items/index.html.erb
- spec/features/menu_items/index_spec.rb
- spec/features/restaurants/menu_items/index_spec.rb
What I did:
Add link to delete menu items from both menu item index pages
> Complete user story 23

- app/controllers/bar_drinks_controller.rb
- app/models/drink.rb
- app/views/bar_drinks/index.html.erb
- spec/features/bars/drinks/index_spec.rb
- spec/models/drink_spec.rb
What I did:
Created a search field to find the threshold of bar drinks. Wrote model and bar drink tests to make sure the filtering is correct. Tests pass with 100% coverage.
> Add search field to search for a threshold of bar drinks

- app/controllers/restaurant_menu_items_controller.rb
- app/models/menu_item.rb
- app/views/restaurant_menu_items/index.html.erb
- spec/features/restaurants/menu_items/index_spec.rb
- spec/models/menu_item_spec.rb
What I did:
Complete user story 21
> Search field
